### ISSUE TITLE
[odoo 10] Website style manager - uninstallable 

### ISSUE THREAD

**Issue by sharkutz** [SythilTech/Odoo10#5] opened 2017-04-12 12:21 UTC
Modules doesn't open side bar in frontend to edit CSS. 
From backend it works.
BUT not able to uninstall the module at all.
Please assist! :+1:

**Comment by SythilTech** [comment] 2017-04-14 07:11
Hello,Sorry I can't reproduce your issue with the sidebar not opening can you please open the JavaScript console on your browser and send me any errors when trying to open the sidebar.Also if you get any error window come up when you try to uninstall can you please send me that code too.RegardsStevenOn 12 Apr 2017 10:21 PM, sharkutz <notifications@github.com> wrote:Modules doesn't open side bar in frontend to edit CSS.
From backend it works.
BUT not able to uninstall the module at all.
Please assist! 👍

**Comment by sharkutz** [comment] 2017-04-14 07:30
I can't reproduce as I had to do a force uninstall. I think the issue is with the fact that I had theme graphene installed. With no theme it works
I think we can close the issue.

**Comment by SythilTech** [comment] 2017-04-14 07:46
Ok good to know you resolved the issue yourself, I shall close this issue now.

**Closed by SythilTech** 2017-04-14 07:46 UTC
